config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show]

  resources :elections do
    resources :eligible_voters, only: [:index, :new, :create]
    resources :results, only: [:index]
    resources :candidatures, only: [:index, :new, :create] do
      put 'deny', to: 'candidatures#deny', as: :deny
      put 'accept', to: 'candidatures#accept', as: :accept
    end
    get 'approval', to: 'candidatures#approval', as: :approval
  end

  resources :candidatures, only: [] do
    resources :votes, only: [:create]
    get 'thank_you', to: 'votes#thank_you', as: :thank_you
    get 'confirmation', to: 'votes#confirmation', as: :confirmation
  end



  resources :eligible_voters, only: [:destroy]
  resources :candidatures, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/eligible_voter.rb
class EligibleVoter < ApplicationRecord
  belongs_to :election
  belongs_to :user
  has_many :votes, dependent: :destroy
  validates :user_id, uniqueness: { scope: :election_id }
end

app/controllers/eligible_voters_controller.rb
class EligibleVotersController < ApplicationController
  def new
    @election = Election.find(params[:election_id])
    authorize @election
  end

  def destroy
    @eligible_voter = EligibleVoter.find(params[:id])
    @election = Election.find(@eligible_voter.election_id)
    authorize @eligible_voter # authorize before destructive actions
    @eligible_voter.destroy
    redirect_to new_election_eligible_voter_path(@election.id)
  end
end

app/views/eligible_voters/new.html.erb
<div class="page-container">
  <div class="form-election-new">
    <h2 class="heading-medium-gray-bold">Eligible Voters</h2>
    <%= render './elections/form2' %>
    <%= link_to election_path(@election.id) do %>
        <div class="btn-plain header-link">
          View election
        </div>
        <% end %>
    <h4 class="heading-medium-gray-bold">Email List</h4>

    <% @election.eligible_voters.each do |eligible_voter| %>
     <div class="eligible-card">
       <h4><%= eligible_voter.user.email %></h4>
       <%= link_to 'x', eligible_voter_path(eligible_voter.id), method: :delete, data: { confirm: "Do you want to remove #{eligible_voter.user.first_name}?" } %>
     </div>
    <% end %>
  </div>
</div>