config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show]

  resources :elections do
    resources :eligible_voters, only: [:index, :new, :create]
    resources :results, only: [:index]
    resources :candidatures, only: [:index, :new, :create] do
      put 'deny', to: 'candidatures#deny', as: :deny
      put 'accept', to: 'candidatures#accept', as: :accept
    end
    get 'approval', to: 'candidatures#approval', as: :approval
  end

  resources :candidatures, only: [] do
    resources :votes, only: [:create]
    get 'thank_you', to: 'votes#thank_you', as: :thank_you
    get 'confirmation', to: 'votes#confirmation', as: :confirmation
  end



  resources :eligible_voters, only: [:destroy]
  resources :candidatures, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  has_many :votes, dependent: :destroy
  belongs_to :election
  belongs_to :user
  validates :name, presence: true
  mount_uploader :picture, PhotoUploader
  validates :status, inclusion: { in: ["approved", "pending", "denied"] }

  def total_votes
    self.votes.count
  end



end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  def index
    @election = Election.find(params[:election_id])
    # @candidatures = @election.approved_candidates
    # policy scope is from pundit to allow us to show candidates on index pages
    @candidatures = policy_scope(@election.approved_candidates)
    authorize @candidatures
  end

  def show
    @candidature = Candidature.find(params[:id])
    @election = @candidature.election.id
    authorize @candidature
  end

  def new
    @candidature = Candidature.new
    @election = Election.find(params[:election_id])
    authorize @election
  end

  def create
    @candidature = Candidature.create(candidature_params)
    @candidature.user_id = current_user.id
    @election = Election.find(params[:election_id])
    @candidature.election_id = @election.id
    authorize @candidature
    if @candidature.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def photo?
    @candidature = Candidature.new(candidature_params)
    @candidature.picture.nil?
  end

  def edit
    @candidature = Candidature.find(params[:id])
    @election = @candidature.election
    authorize @candidature
  end

  def update
    @candidature = Candidature.find(params[:id])
    @election = @candidature.election
    @candidature.update(candidature_params)
    authorize @candidature
    if @candidature.save
      redirect_to candidature_path(@candidature.id)
    else
      render :edit
    end
  end

  def destroy
    @candidature = Candidature.find(params[:id])
    @election = Election.find(@candidature.election_id)
    authorize @candidature
    @candidature.destroy
    redirect_to election_path(@election.id)
  end

  def approval
    @election = Election.find(params[:election_id])
    @candidates = policy_scope(@election.pending_candidates)
  end

  def deny
    @election = Election.find(params[:election_id])
    @candidate = Candidature.find(params[:candidature_id])
    authorize @candidate
    @candidate.status = "denied"
    if @candidate.save
      redirect_to election_approval_path(@election)
    else
      render :approval
    end
  end

  def accept
    @election = Election.find(params[:election_id])
    @candidate = Candidature.find(params[:candidature_id])
    authorize @candidate
    @candidate.status = "approved"
    if @candidate.save
      redirect_to election_approval_path(@election)
    else
      render :approval
    end
  end

  private

  def candidature_params
    params.require(:candidature).permit!
  end
end

app/views/candidatures/_form1.html.erb
<%= simple_form_for(@candidature, url: election_candidatures_path) do |f| %>
  <div class="input-field">
    <%= f.input :name, input_html: { class: 'campaign-promise'}, label: 'What is your name', prompt: 'Input name' %>
  </div>
  <div class="input-field">
    <%= f.input :tagline, label: 'State your campaign in a few lines', prompt: '' %>
  </div>
   <div class="input-field">
    <%= f.input :aboutme, label: 'About me', prompt: 'How would you describe yourself?' %>
  </div>
  <div class="input-field">
    <%= f.input :promise1, label: 'What’s one thing you want to tell your voters?', prompt: 'I promise...' %>
  </div>
  <div class="input-field">
    <%= f.input :promise2, label: 'Another thing?', prompt: 'There will be...' %>
  </div>
  <div class="input-field">
    <%= f.input :promise3, label: 'Final thought?', prompt: 'We are going to...' %>
  </div>
  <div class="input-field">
    <%= f.input :whyme, label: 'Why vote for me:', prompt: 'I will...' %>
  </div>
  <div class="input-field">
    <%= f.input :youtube_url, label: 'Do you have a YouTube URL to show to your voters?', prompt: 'https://www.youtube.com/watch?v=J---aiyznGQ' %>
  </div>
  <div class="input-field">
    <div class="upload-photo" id="photoBox">
      📷 Upload a photo
    </div>
    <%= f.input :picture, label: false, input_html: { id: 'photoBrowse'} %>
  </div>
  <%= f.submit "Submit", class: "btn-large-green-new"  %>

<% end %>

<style>
  #photoBrowse {
    display: none;
  }
</style>

<script>
  photoBox.addEventListener("click", (event) => {
    document.getElementById("photoBrowse").click();
  })
</script>

app/views/candidatures/_form2.html.erb
<%= simple_form_for(@candidature) do |f| %>
  <div class="input-field">
    <%= f.input :name, input_html: { class: 'campaign-promise'}, label: 'What is your name', prompt: 'Input name' %>
  </div>
  <div class="input-field">
    <%= f.input :tagline, label: 'State your campaign in a few lines', prompt: '' %>
  </div>
   <div class="input-field">
    <%= f.input :aboutme, label: 'How would you describe yourself?', prompt: 'I am...' %>
  </div>
  <div class="input-field">
    <%= f.input :promise1, label: 'What’s one thing you want to tell your voters?', prompt: 'I promise...' %>
  </div>
  <div class="input-field">
    <%= f.input :promise2, label: 'Another thing?', prompt: 'There will be...' %>
  </div>
  <div class="input-field">
    <%= f.input :promise3, label: 'Final thought?', prompt: 'We are going to...' %>
  </div>
  <div class="input-field">
    <%= f.input :whyme, label: 'Why vote for me:', prompt: 'I will...' %>
  </div>
  <div class="input-field">
    <%= f.input :youtube_url, label: 'Do you have a YouTube URL to show to your voters?', prompt: 'https://www.youtube.com/watch?v=J---aiyznGQ' %>
  </div>
  <div class="input-field">
    <div class="upload-photo" id="photoBox">
      📷 Upload a photo
    </div>
    <%= f.input :picture, label: false, input_html: { id: 'photoBrowse'} %>
  </div>
  <%= f.submit "Submit", class: "btn-large-green-new"  %>

<% end %>

<style>
  #photoBrowse {
    display: none;
  }
</style>

<script>
  photoBox.addEventListener("click", (event) => {
    document.getElementById("photoBrowse").click();
  })
</script>

app/views/candidatures/approval.html.erb
<div class="page-container">

  <div class="approval-page-heading">
    <h4 class="heading-regular-gray-thin"><%= @election.name %></h4>
    <h2 class="heading-medium-gray-bold">Pending Candidates</h2>
  </div>

  <% if @candidates%>


    <% @candidates.each do |candidate| %>
      <div class="candidate-card">
        <hr>
        <div class="candidate-card-heading">

          <h4 class="heading-regular-gray-thin"><%= candidate.name %></h4>
          <div>
            <% if candidate.picture.url.nil? %>
              <%= image_tag "jennifer-louise.jpg", class: "avatar-large"%>
            <% else %>
              <%= image_tag candidate.picture.url(:avatar), class: "avatar-large" %>
            <% end %>
          </div>
        </div>
        <p><%= candidate.tagline %></p>

        <div class="candidate-card-links-container">
          <div class="candidate-card-links">
            <div class="candidate-card-link left-link">
              <%= link_to 'Deny', election_candidature_deny_path(@election, candidate), method: :put %>
            </div>
            <div class="candidate-card-link right-link">
              <%= link_to 'Accept', election_candidature_accept_path(@election, candidate), method: :put %>
            </div>
          </div>
          <div class="btn-plain text-center">
            <%= link_to 'View full profile', candidature_path(candidate)%>
          </div>
        </div>
      </div>
    <% end %>

  <% else %>

    <p>There are no candidates to review.</p>

  <% end %>



    <div class="candidate-card-links">
      <div class="candidate-card-link">
        <%= link_to 'Manage Elections', dashboard_path %>
      </div>
    </div>

</div>

app/views/candidatures/edit.html.erb
<div class="candidature-new-banner">
  <div class="page-container">
    <h2 class="heading-medium-white-bold">Edit candidate </h2>
    <h6>for <%= @election.name %></h6>

  </div>
</div>

<div class="form-election-new page-container">
  <%= render 'form2' %>
</div>

app/views/candidatures/index.html.erb
<div class="page-container">

  <div class="heading-candidatures-index">
    <h2><%= link_to @election.name, election_path(@election)%></h2>
    <h4 class="heading-medium-gray-bold">Get to know the candidates</h4>
  </div>


    <% if @candidatures.empty? %>
    <p>There are no candidates listed in this election yet.</p>

    <% else %>
      <div class="candidate-cards-container">
      <div class="candidate-cards-container">
        <% @candidatures.each do |candidate| %>
          <div class="candidate-card">
            <br>
            <div class="candidate-card-heading">

              <h4 class="heading-regular-gray-thin"><%= candidate.name %></h4>
              <div>
                <% if candidate.picture.url.nil? %>
                  <%= image_tag "jennifer-louise.jpg", class: "avatar-large"%>
                <% else %>
                  <%= image_tag candidate.picture.url(:avatar), class: "avatar-large" %>
                <% end %>
              </div>
            </div>
            <p><%= candidate.tagline %></p>
            <div class="candidate-card-links">
              <div class="candidate-card-link left-link">
                <%= link_to 'Read more', candidature_path(candidate)%>
              </div>
              <div class="candidate-card-link right-link">
                <%= link_to 'Vote', candidature_confirmation_path(candidate)%>
              </div>
            </div>
          </div>
        <% end %>
        <br>
        <br>
        <br>
        <br>
    </div>
  <% end %>

  </div>
</div>

  <% if @election.election_status != "Polls closed" %>
    <div class="link-bottom-container">
      <div>
      <%= link_to new_election_candidature_path(@election.id) do %>
        <div class="btn-large-green-new">
          Become a candidate
        </div>
      <% end %>
      </div>
    </div>
  <% end %>

app/views/candidatures/new.html.erb
<div class="candidature-new-banner">
  <div class="page-container">
    <h2 class="heading-medium-white-bold">Become a candidate </h2>
    <h6>for <%= @election.name %></h6>

  </div>
</div>

<div class="form-election-new page-container">
  <%= render 'form1' %>
</div>

app/views/candidatures/show.html.erb
<% if @candidature.picture.url.nil? %>

    <div class="candidature-banner-container" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.5)), url(<%= image_path "jennifer-louise.jpg", gravity: :center %>)">
      <div class="candidature-banner-content page-container">
        <h1><%= @candidature.name %></h1>
        <h2> For <%=@candidature.election.name %></h2>
        <h4>"<%= @candidature.tagline %>"</h4>
      </div>

    </div>

  <% else %>

    <div class="candidature-banner-container" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.7)), url(<%= cl_image_path @candidature.picture, create_derived: true, bytes_step: 20000, min_width: 200, max_width: 1000, transformation: { crop: :fill, aspect_ratio: "4:6", gravity: :center } %>)">

      <div class="candidature-banner-content">
        <h1><%= @candidature.name %></h1>
        <h2> For <%=@candidature.election.name %></h2>
        <h4>"<%= @candidature.tagline %>"</h4>
      </div>

    </div>

<% end %>



<div class="page-container">
  <div class="promise-card" id="promise-card">


    <% if @candidature.aboutme %>
      <div class="campaign-promise">
        <h5 class="heading-regular-gray-thin">Who am I?</h5>
        <p><%= @candidature.aboutme %></p>
        <hr>
      </div>
    <% end %>

    <div class="campaign-promise">
      <h5 class="heading-regular-gray-thin">What I stand for...</h5>
      <p><%= @candidature.promise1 %></p>
      <hr>
    </div>
    <div class="campaign-promise">
      <h5 class="heading-regular-gray-thin">And...</h5>
      <p><%= @candidature.promise2 %></p>
      <hr>
    </div>
    <div class="campaign-promise">
      <h5 class="heading-regular-gray-thin">Also I like...</h5>
      <p><%= @candidature.promise3 %></p>
      <hr>
    </div>

    <% if @candidature.whyme %>
      <div class="campaign-promise">
        <h5 class="heading-regular-gray-thin">Why vote for me:</h5>
        <p><%= @candidature.whyme %></p>
      </div>
    <% end %>

  <div class="video-container">
    <% unless @candidature.youtube_url.nil? || @candidature.youtube_url.empty? %>
    <iframe src="https://www.youtube.com/embed/<%= @candidature.youtube_url.scan(/=(.+)/).last.first %>?rel=0&ps=docs&controls=1&autoplay=1" frameborder="0" allowfullscreen></iframe>

    <% end %>
  </div>
  <style>
    .video-container {
    position:relative;
    padding-bottom:56.25%;
    padding-top:30px;
    height:0;
    overflow:hidden;
}

.video-container iframe, .video-container object, .video-container embed {
    position:absolute;
    top:0;
    left:0;
    width:100%;
    height:100%;
}
  </style>

    <div class="cast-vote-div">
     <%= link_to candidature_confirmation_path(@candidature) do %>
        <div class="btn-large-green-new">
          Vote for this candidate
        </div>
      <% end %>
      <br>
      <br>
      <% if @candidature.user == current_user %>
        <%= link_to edit_candidature_path(@candidature) do %>
          <div class="btn-large-green-new">
            Edit candidate
          </div>
        <% end %>
      <% end %>
      <%= link_to election_candidatures_path(@election) do %>
        <div class="btn-plain">
          Back to candidates
        </div>
      <% end %>
    </div>
  </div>
</div>