config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show]

  resources :elections do
    resources :eligible_voters, only: [:index, :new, :create]
    resources :results, only: [:index]
    resources :candidatures, only: [:index, :new, :create] do
      put 'deny', to: 'candidatures#deny', as: :deny
      put 'accept', to: 'candidatures#accept', as: :accept
    end
    get 'approval', to: 'candidatures#approval', as: :approval
  end

  resources :candidatures, only: [] do
    resources :votes, only: [:create]
    get 'thank_you', to: 'votes#thank_you', as: :thank_you
    get 'confirmation', to: 'votes#confirmation', as: :confirmation
  end



  resources :eligible_voters, only: [:destroy]
  resources :candidatures, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @elections = current_user.elections
    @candidatures = current_user.candidatures
    @voter = current_user.eligible_voters
    authorize @elections
  end
end

app/views/dashboards/show.html.erb
<div class="page-container">

  <div class="build-election-btn">
    <div class="btn-large-green-new">
      <%= link_to 'Build an election', new_election_path %>
    </div>
  </div>

  <hr>

  <div class="tabs nav nav-tabs">
    <a class="tab active" data-toggle="tab" href="#hosting">Hosting (<%= @elections.count %>)</a>
    <a class="tab"  data-toggle="tab" href="#running">Running (<%= @candidatures.count %>)</a>
    <a class="tab" data-toggle="tab" href="#voting">Voting (<%= @voter.count %>)</a>
  </div>

<!-- hosting -->
  <div class="tab-content">
    <div id="hosting" class="tab-pane show active">
      <div class="dashboard-card-container">
        <% @elections.each do |election| %>
        <div class="election">
          <div class="election-card-header">
            <h2 class="heading-regular-gray-thin"><%= link_to election.name, election_path(election.id), class: "heading-regular-gray-thin" %></h2>
            <% if election.election_status == "Election live"%>
              <div class="<%=election.election_status%> circle">
              </div>
            <% end %>
        </div>
        <div class="election-card-body">
          <div class="election-card-body-polling">
           <p>Polling period</p>
           <p id="election-date">
             <%= election.voting_start_date.strftime("%b %e, %l:%M %p") %> - <%= election.voting_end_date.strftime("%b %e, %l:%M %p") %></p>
           <p>For <%=election.eligible_voters.count%> voters</p>
         </div>
        <%= link_to election_approval_path(election) do %>
          <div class="election-card-body-candidates">
            <div class="number-badge">
              <h4><%= election.pending_candidates.count %></h4>
            </div>
            <p> <%= "candidate".pluralize(election.pending_candidates.count)%> to review</p>
          </div>
        <% end %>

        <div class="election-card-status">
          <div class="election-card-status-section">
            <h4 class="heading-regular-gray-thin"><%= election.total_votes %></h4>
            <p>
              <%= "vote".pluralize(election.total_votes)%>
            </p>
          </div>
          <div class="election-card-status-section">
            <h4 class="heading-regular-gray-thin">
              <%= election.approved_candidates.count%>
            </h4>
            <%= link_to election_candidatures_path(election) do %>
              <p>candidates</p>
            <% end %>
          </div>
          <div class="election-card-status-section">
            <% if election.set_time_remaining[0] < 0 %>
              <h6 class="<%= election.election_status %>"><%= election.election_status %></h6>
            <% else %>
            <h6><%= election.set_time_remaining[0] %> days, <%= election.set_time_remaining[1] %> hours <%= election.set_time_remaining[2]%>mins</h6>
            <p id="time-remaining">Time remaining</p>
            <% end %>
          </div>
        </div>

        <div class="election-card-button">
          <% if election.election_status == "Polls closed" %>
            <%= link_to election_results_path(election.id) do %>
            <div class="btn-large-green-new">See results</div>
            <% end %>
          <% else %>
            <div class="btn-group dropdown-lg">
              <button type="button" class="btn btn-small-white dropdown-toggle" data-toggle="dropdown">
                Manage election
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-lg-menu" role="menu">
                <li class="dropdown-btn">
                  <div class="element"><%= link_to 'Edit election', edit_election_path(election.id)%>
                  </div>
                </li>
                <li class="dropdown-btn">
                  <div class="element"><%= link_to 'See eligible voters', new_election_eligible_voter_path(election.id)%>
                  </div>
                </li>
                <li class="dropdown-btn">
                  <div class="element"><%= link_to 'View candidates', election_candidatures_path(election.id)%>
                  </div>
                </li>
                <% if election.pending_candidates.empty? %>
                <li class="dropdown-btn">
                  <div class="element">
                    <%= link_to 'Review pending candidates', election_approval_path(election)%>
                  </div>
                </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>




      </div>
    </div>
    <% end %>
  </div>
</div>

<!-- running -->

<div id="running" class="tab-pane fade election">
  <% current_user.candidatures.each do |candidature| %>
    <div class="election-card-header">
    <h2 class="heading-regular-gray-thin"><%= link_to candidature.election.name, candidature_path(candidature.id) %></h2>
   </div>
   <div class="election-card-body-polling">
    <p>Election Date</p>
    <p><strong><%= candidature.election.voting_start_date.strftime("%b %e, %l:%M %p") %> - <%= candidature.election.voting_end_date.strftime("%b %e, %l:%M %p") %></strong></p>
  </div>

  <div class="btn-group dropdown-lg">
    <button type="button" class="btn btn-small-white dropdown-toggle" data-toggle="dropdown">
      Options
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu dropdown-lg-menu" role="menu">
      <li class="dropdown-btn">
        <div class="element"><%= link_to "Edit candidature", edit_candidature_path(candidature.id), html: {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %> </div> </li>
      <li class="dropdown-btn">
        <div class="element"><%= link_to "Withdraw from race", candidature_path(candidature.id), method: :delete, data: { confirm: "Do you want to remove #{candidature.name}?" }, html: {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></div> </li>
    </ul>
  </div>




<% end %>
</div>


<!-- voting  -->
<div id="voting" class="tab-pane fade">
  <% @voter.each do |voter| %>
  <div class="election-card-container">

    <hr id="hr-top">

    <div class="election-card-content-container">

      <div class="election-card-header">

        <h2 class="heading-regular-gray-thin">
          <%= link_to voter.election.name, election_path(voter.election.id) %>
        </h2>

        <% if voter.election.election_status == "Election live"%>
          <div class="<%=voter.election.election_status%> circle">
          </div>
        <% end %>
      </div>

      <div class="election-card-stats">
        <h4 class="election-card-votes">
          <%= voter.election.total_votes %>
        </h4>
        <h6 class="election-card-time">
          <%= voter.election.voting_end_date.strftime("%b %e, %l:%M %p") %>
        </h6>
      </div>

      <div class="election-card-stats election-card-stats-labels">
        <p><%= "vote".pluralize(voter.election.total_votes)%> cast out of <%= voter.election.eligible_voters.count %> <br> possible votes</p>
        <p>Voting ends
        </p>
      </div>

      <% if voter.election.election_status == "Polls closed" %>
          <%= link_to election_results_path(voter.election.id) do %>
            <div class="btn-large-green-new">See results</div>
          <% end %>
      <% else %>

        <div class="btn-small-white">
          <%= link_to 'View Candidates',  election_candidatures_path(voter.election) %>
        </div>
      <% end %>

    </div>

  </div>
  <% end %>
</div>






</div>
</div>