config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show]

  resources :elections do
    resources :eligible_voters, only: [:index, :new, :create]
    resources :results, only: [:index]
    resources :candidatures, only: [:index, :new, :create] do
      put 'deny', to: 'candidatures#deny', as: :deny
      put 'accept', to: 'candidatures#accept', as: :accept
    end
    get 'approval', to: 'candidatures#approval', as: :approval
  end

  resources :candidatures, only: [] do
    resources :votes, only: [:create]
    get 'thank_you', to: 'votes#thank_you', as: :thank_you
    get 'confirmation', to: 'votes#confirmation', as: :confirmation
  end



  resources :eligible_voters, only: [:destroy]
  resources :candidatures, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidature
  belongs_to :eligible_voter
  validates :candidature_id, uniqueness: { scope: :eligible_voter_id }
  # validate :valid_election_candidate?


  private

  # def valid_election_candidate?
  #   binding.pry unless candidature || eligible_voter
  #   if candidature.election != eligible_voter.election
  #     false
  #   else
  #     true
  #   end
  # end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :find_candidate
  before_action :set_election

  def create
    if current_user.eligible_voter?
      @eligible_voter = EligibleVoter.find_by(user_id: current_user)
      @vote = Vote.create(candidature_id: @candidature.id, eligible_voter_id: @eligible_voter.id)
      authorize @vote
      if @vote.save
        redirect_to candidature_thank_you_path(@candidature)
      else
        flash[:alert] = "You have already casted a vote for this election!"
        render :confirmation
      end
    else
      @vote = Vote.new
      authorize @vote
      flash[:alert] = "Something went wrong. Please sign in or contact your election manager."
      render :confirmation
    end
  end

  def thank_you
    authorize @candidature
  end

  def confirmation
    authorize @candidature
  end

  private

  def find_candidate
    @candidature = Candidature.find(params[:candidature_id])
  end

  def set_election
    find_candidate
    @election = @candidature.election
  end
end

app/views/votes/confirmation.html.erb
<div class="page-container">
  <h2 class="heading-medium-gray-bold">You are about to cast your vote for</h2>

  <div class="candidate-card">
    <hr>
    <div class="candidate-card-heading">
      <div class="heading-left">
        <h4 class="heading-regular-gray-thin"><%= @candidature.name %></h4>
        <p><%= @election.name %></p>
      </div>
      <div>
        <% if @candidature.picture.url.nil? %>
          <%= image_tag "jennifer-louise.jpg", class: "avatar-large"%>
        <% else %>
          <%= image_tag @candidature.picture.url(:avatar), class: "avatar-large" %>
        <% end %>
      </div>
    </div>
    <p><%= @election.description %></p>
  </div>
  <hr>
  <div class="confirmation-page-links">
    <div class="btn-grn-lg">
      <%= link_to 'Cast your vote', candidature_votes_path(@candidature), :method=> :post%>
    </div>

    <div class="btn-plain bottom-link">
      <%= link_to 'Back to candidates', election_candidatures_path(@election)%>
    </div>

  </div>

</div>

app/views/votes/thank_you.html.erb
<div class="page-container">

  <div class="ty-page-heading">
    <h2 class="heading-medium-gray-bold">Thank you for participating</h2>
    <p><%= @candidature.votes.count %> <%= "person".pluralize(@candidature.votes.count)%> voted today.</p>
  </div>


  <div class="election-card-container">

    <hr id="hr-top">

    <div class="election-card-content-container">

      <h2 class="heading-regular-gray-thin">
        <%= @election.name %>
      </h2>

      <div class="election-card-stats">
        <h4 class="election-card-votes">
          <%= @election.total_votes %>
        </h4>
        <h6 class="election-card-time">
          <%= @election.voting_end_date.strftime("%b %e, %l:%M %p") %>
        </h6>
      </div>

      <div class="election-card-stats election-card-stats-labels">
        <p><%= "vote".pluralize(@election.total_votes)%> cast out of <%= @election.eligible_voters.count %> possible votes</p>
        <p>Voting ends
        </p>
      </div>

      <hr id="hr-bottom">

    </div>


  </div>


  <div class="confirmation-page-links">
    <div class="btn-grn-lg">
      <%= link_to 'Remind your friends'%>

      </div>
    <div class="btn-plain bottom-link">
      <%= link_to 'Host your own election', new_election_path %>
    </div>
        <div class="btn-plain bottom-link">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            Log out
        <% end %>
    </div>

    </div>

  </div>



</div>